name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Validate files
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
        root: "."
        css: true
        Log_Level: DEBUG 
        
    - uses: actions/upload-artifact@v1
      with:
        name: log
        path: log.log
